# This compose fragment describes development environment
# modifications to the original compose file.
version: "3"
services: 
  api:
    env_file: ./env/prod/prod.env
    image: api:prod
    build:
      context: .
      dockerfile: ./env/Dockerfile
    ports:
      - "3999:3999"