# This compose fragment describes development environment
# modifications to the original compose file.
version: "3"
services: 
  api:
    env_file: ./env/local/local.env
    image: api:local
    build:
      context: .
      dockerfile: ./env/Dockerfile
    ports:
      - "3999:3999"
    links:
      - postgres
  postgres:
    env_file: ./env/local/local.env
    image: postgres:10.3
    ports:
      - "5432:5432"
    volumes:
          - ./db/postgres/init:/docker-entrypoint-initdb.d/