# This compose fragment describes development environment
# modifications to the original compose file.
version: "3"
services: 
  goblog:
    env_file: ./env/stage/stage.env
    image: api:stage
    build:
      context: .
      dockerfile: ./env/Dockerfile
    ports:
      - "3999:3999"